### PR TITLE
Replaces slice_deque with slice_ring_buffer (maintained fork)

### PR DESCRIPTION
**Pull request by LiquidityC**
Fixes: #29

### CODE REVIEW

**Comment by germangb** [comment]
Thanks for the PR. I'm a bit busy lately but soon I will have free time to catch up

**Comment by LiquidityC** [comment]
No worries. In your own time

**Comment by ArthurKValladares** [comment]
Thanks so much for the PR. This touches some code that causes apps using this crate to fail App Store Certification, which we can fix by exposing a `slice_ring_buffer` crate feature like I did here:
https://github.com/LiquidityC/minimp3-rs/pull/1

**Comment by ImUrX** [comment]
@germangb any news?

**Comment by est31** [comment]
@germangb I've received https://github.com/RustAudio/rodio/pull/504 and will merge it, but would love if this PR could be merged (or maintenance be given to other people) so that I can switch back to the proper `minimp3`.

**Pull request closed without merging**
