### PR TITLE
Write a safe wrapper around the generated bindings

### PR DESCRIPTION
**Pull request by barzamin**
As in title. See `examples/example.rs` for usage.

Moves the unsafe bindings to a separate crate, `minimp3-sys`.

These changes make it possible to safely integrate `minimp3` into Rodio and _finally_ make progress towards closing tomaka/rodio#36.

- [x] `Decoder` abstraction
  - [x] Frame decoding
  - [x] Manages filling data buffer from a `R: Read`
- [x] Docs

### CODE REVIEW

**Comment by germangb** [comment]
Hi @barzamin, thank you for opening this PR, I'm looking forward to merging it.

If you don't mind, I'll check it out when I find some spare time during this week.

**Comment by barzamin** [comment]
Oops, forgot to mention I do need to fix potential stack-blowing due to [this recursion](https://github.com/germangb/minimp3-rs/pull/1/files#diff-b4aea3e418ccdb71239b96952d9cddb6R94) if there are large numbers of contiguous skipped frames. That's an ugly hack left over from dev and needs to go away. [This one](https://github.com/germangb/minimp3-rs/pull/1/files#diff-b4aea3e418ccdb71239b96952d9cddb6R89( is probably fine but maybe I should consider refactoring to remove both?

**Comment by germangb** [comment]
Thanks!

**Comment by barzamin** [comment]
@germangb any chance you could push the new `minimp3` version and the `minimp3-sys` crate to crates.io?

**Pull request merged**
